# Generated by Django 3.2.6 on 2021-08-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesadmin',
            old_name='adminuplaod',
            new_name='adminupload',
        ),
    ]
